# Site settings
name: Liang Ou
location: 大连
company: IBM
position: Java开发工程师
github: https://github.com/
facebook: https://www.facebook.com/
phone: 1580424XXXX
email: xxxx@xxx.com

baseurl: "https://ouliang0128.github.io/Liang_HomePage/"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

