# Site settings
name: Liang Ou
location: UTS Housing, Yura Mudang residence, 1501, 702-730 Harris Street, Ultimo NSW 2007, Australia
company: University of Technology Sydney (UTS)
position: Student
github: https://github.com/ouliang0128
facebook:
phone: 0411853109
email: ouliang0128@outlook.com

#baseurl: "/resume.io"
baseurl: "https://ouliang0128.github.io/"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

