# Site settings
name: Liang Ou
location: Sydney, Australia
company: University of Technology Sydney (UTS)
position: Student
github: https://github.com/ouliang0128/
facebook: https://www.facebook.com/
phone: (0411) 853 109
email: ouliang0128@outlook.com

baseurl: "https://ouliang0128.github.io/Liang_HomePage/"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown


theme: jekyll-theme-cayman
